name: On PR Merge to 2024

on:
  pull_request:
    types:
      - closed

jobs:
  notify:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.base.ref, '2024') && contains(github.event.pull_request.head.ref, 'test-')
    runs-on: ubuntu-latest
    steps:
      - name: Echo branch name
        run: 'echo "Done! Branch: ${{ github.event.pull_request.head.ref }}"'
