name: unit tests
run-name: runs unit tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

    - name: Install dependencies
      run: bundle install

    - name: Run RSpec
      run: bundle exec rspec