name: On PR Merge to 2024

on:
  pull_request:
    types:
      - closed
    paths:
      - 'year20[0-9][0-9]'

jobs:
  notify:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.head.ref, 'test-')
    runs-on: ubuntu-latest
    steps:
      - name: Echo branch name
        run: 'echo "Done! Branch: ${{ github.event.pull_request.head.ref }}"'
