name: On PR Merge to 2024

on:
  pull_request:
    types:
      - closed

jobs:
  notify:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.base.ref, '2024') && contains(github.event.pull_request.head.ref, 'test-')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write 
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Append a word to README.md
        run: |
          echo "nueva_palabra" >> README.md
          echo "Updating calendar..."
          DAY=$(echo "${{ github.head_ref }}" | grep -oP '\d+')
          YEAR=$(echo "${{ github.ref }}" | grep -oP '20[0-9][0-9]')
          echo "DAY: $DAY"
          echo "YEAR: $YEAR"
          README_FILE="README.md"
          TEMP_FILE="README_TEMP.md"
          # Read the README file and update the specific day
          awk -v day="$DAY" '{
            if ($0 ~ "\\| " day " \\|") {
              gsub("\\| " day " \\|", "| " day "✅ |")
            }
            print
          }' $README_FILE > $TEMP_FILE
          
          mv $TEMP_FILE $README_FILE

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Update README after PR merge"
          git push origin ${{ github.ref }}