name: On PR Merge to 2024

on:
  pull_request:
    types:
      - closed

jobs:
  notify:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.base.ref, '2024') && contains(github.event.pull_request.head.ref, 'test-')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write 
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Append a word to README.md
        run: echo "nueva_palabra" >> README.md

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Update README after PR merge"
          git push origin ${{ github.ref }}