name: Update Calendar

on:
  push:
    branches:
      - '20[0-9][0-9]' # Matches branches like 2019, 2020, 2021, etc.
    paths:
      - 'day-*' # Matches branches like day-1, day-2, etc.

jobs:
  update-calendar:
    if: contains(github.ref, '20[0-9][0-9]') && contains(github.head_ref, 'day-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update calendar
        run: |
          echo "Updating calendar..."
          DAY=$(echo "${{ github.head_ref }}" | grep -oP '\d+')
          YEAR=$(echo "${{ github.ref }}" | grep -oP '20[0-9][0-9]')
          README_FILE="README.md"
          TEMP_FILE="README_TEMP.md"
          
          # Read the README file and update the specific day
          awk -v day="$DAY" '{
            if ($0 ~ "\\| " day " \\|") {
              gsub("\\| " day " \\|", "| " day "✅ |")
            }
            print
          }' $README_FILE > $TEMP_FILE
          
          mv $TEMP_FILE $README_FILE
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add $README_FILE
          git commit -m "Update calendar for day ${DAY} of ${YEAR}"
          git push